name: "Giulie_Omg_Te_amo"
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  image_picker: ^1.0.7
  table_calendar: ^3.1.3
  uuid: ^4.5.2
  timezone: ^0.10.1
  http: ^1.1.0
  screen_brightness: ^1.0.1 
  path_provider: ^2.1.1 
  path: ^1.8.3        
  flutter_local_notifications: ^19.0.0
  fl_chart: ^0.66.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets (imagens, fontes, etc)
  assets:
    - assets/images/